import { Feather, Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Polyline } from 'react-native-svg';
import { useColors } from '@/hooks/useColors';
import { MarketAsset, NewsItem } from '@/src/models';
import { useWatchlist } from '@/src/context/WatchlistContext';

export const formatPrice = (value: number) => value >= 1000 ? '$' + value.toLocaleString('en-US', { maximumFractionDigits: 0 }) : value < 1 ? '$' + value.toFixed(4) : '$' + value.toFixed(2);
export const formatPercent = (value: number) => (value >= 0 ? '+' : '') + value.toFixed(2) + '%';
export const formatCategory = (category: string) => ({ MARKET: '시장', ETF: 'ETF', MACRO: '거시경제', DEFI: '디파이', ALTCOIN: '알트코인', EXCHANGE: '거래소', LISTING: '상장' }[category] ?? category);

export function ScreenHeader({ eyebrow, title, onPress }: { eyebrow: string; title: string; onPress?: () => void }) {
  const colors = useColors();
  return <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>{eyebrow}</Text><Text style={[styles.headerTitle, { color: colors.foreground }]}>{title}</Text></View>{onPress ? <Pressable testID="header-action" onPress={onPress} style={({ pressed }) => [styles.iconButton, { borderColor: colors.border, backgroundColor: colors.card, opacity: pressed ? 0.7 : 1 }]}><Ionicons name="notifications-outline" size={20} color={colors.foreground} /></Pressable> : <View style={styles.headerMark}><View style={[styles.markDot, { backgroundColor: colors.primary }]} /><Text style={[styles.markText, { color: colors.foreground }]}>MP</Text></View>}</View>;
}

export function Sparkline({ points, color, width = 98, height = 38, strokeWidth = 2 }: { points: number[]; color: string; width?: number; height?: number; strokeWidth?: number }) {
  const min = Math.min(...points); const max = Math.max(...points); const range = max - min || 1;
  const coordinates = points.map((point, index) => `${(index / (points.length - 1)) * width},${height - 4 - ((point - min) / range) * (height - 8)}`).join(' ');
  return <Svg width={width} height={height}><Polyline points={coordinates} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
}

export function MarketCard({ asset, compact = false }: { asset: MarketAsset; compact?: boolean }) {
  const colors = useColors();
  return <Pressable testID={`market-card-${asset.symbol}`} onPress={() => router.push(`/coin/${asset.symbol}`)} style={({ pressed }) => [compact ? styles.marketCardCompact : styles.marketCard, { borderColor: colors.border, backgroundColor: colors.card, opacity: pressed ? 0.76 : 1 }]}><View style={styles.rowBetween}><View style={styles.symbolPill}><View style={[styles.coinDot, { backgroundColor: asset.accent }]} /><Text style={[styles.symbolText, { color: colors.foreground }]}>{asset.symbol}</Text></View><Text style={[styles.changeText, { color: asset.change24h >= 0 ? colors.positive : colors.negative }]}>{formatPercent(asset.change24h)}</Text></View><Text style={[compact ? styles.compactPrice : styles.price, { color: colors.foreground }]}>{formatPrice(asset.price)}</Text><View style={styles.rowBetween}><Text style={[styles.mutedText, { color: colors.mutedForeground }]}>{asset.name}</Text><Sparkline points={asset.sparkline} color={asset.change24h >= 0 ? colors.positive : colors.negative} width={compact ? 82 : 98} height={30} /></View></Pressable>;
}

export function NewsRow({ item, featured = false }: { item: NewsItem; featured?: boolean }) {
  const colors = useColors();
  const categoryLabel = item.importance === 'breaking' ? '속보' : item.categories.map(formatCategory).join(' · ');
  return <Pressable testID={`news-row-${item.id}`} onPress={() => router.push(`/news/${item.id}`)} style={({ pressed }) => [featured ? styles.breakingCard : styles.newsRow, { borderColor: colors.border, backgroundColor: featured ? colors.muted : colors.card, opacity: pressed ? 0.76 : 1 }]}><View style={styles.rowBetween}><View style={styles.categoryLine}><View style={[styles.liveDot, { backgroundColor: item.importance === 'breaking' ? colors.negative : colors.primary }]} /><Text style={[styles.categoryText, { color: item.importance === 'breaking' ? colors.negative : colors.primary }]}>{categoryLabel}</Text><Text style={[styles.timeText, { color: colors.mutedForeground }]}>{item.relativeTime}</Text></View><Text style={[styles.changeText, { color: item.priceChange >= 0 ? colors.positive : colors.negative }]}>{formatPercent(item.priceChange)}</Text></View><Text numberOfLines={featured ? 3 : 2} style={[featured ? styles.breakingTitle : styles.newsTitle, { color: colors.foreground }]}>{item.title}</Text><View style={styles.rowBetween}><View style={styles.tagRow}>{item.relatedSymbols.map((symbol) => <View key={symbol} style={[styles.tinyTag, { backgroundColor: colors.secondary }]}><Text style={[styles.tinyTagText, { color: colors.secondaryForeground }]}>{symbol}</Text></View>)}</View><Text style={[styles.sourceText, { color: colors.mutedForeground }]}>{item.source}</Text></View></Pressable>;
}

export function SectionHeading({ label, action, onAction }: { label: string; action?: string; onAction?: () => void }) {
  const colors = useColors();
  return <View style={styles.sectionHeading}><Text style={[styles.sectionLabel, { color: colors.foreground }]}>{label}</Text>{action && <Pressable testID={`section-action-${label}`} onPress={onAction}><Text style={[styles.actionText, { color: colors.primary }]}>{action}</Text></Pressable>}</View>;
}

export function SentimentCard({ score, label, change }: { score: number; label: string; change: number }) {
  const colors = useColors(); const circumference = 2 * Math.PI * 41; const dash = circumference * (score / 100);
  const sentimentLabel = label === 'GREED' ? '탐욕' : label === 'FEAR' ? '공포' : '중립';
  return <View style={[styles.sentimentCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.rowBetween}><View><Text style={[styles.cardKicker, { color: colors.mutedForeground }]}>시장 심리</Text><Text style={[styles.sentimentLabel, { color: colors.primary }]}>{sentimentLabel}</Text><Text style={[styles.sentimentChange, { color: colors.mutedForeground }]}>+{change.toFixed(1)}점 · 이번 주</Text></View><Svg width={102} height={102}><Circle cx="51" cy="51" r="41" fill="none" stroke={colors.secondary} strokeWidth="8" /><Circle cx="51" cy="51" r="41" fill="none" stroke={colors.primary} strokeWidth="8" strokeDasharray={`${dash} ${circumference}`} strokeLinecap="round" transform="rotate(-90 51 51)" /></Svg></View><Text style={[styles.gaugeNumber, { color: colors.foreground }]}>{score}</Text></View>;
}

export function ImpactWidget({ item }: { item: NewsItem }) {
  const colors = useColors();
  return <Pressable testID="impact-widget" onPress={() => router.push(`/news/${item.id}`)} style={({ pressed }) => [styles.impactCard, { borderColor: colors.border, backgroundColor: colors.card, opacity: pressed ? 0.76 : 1 }]}><View style={styles.impactHeader}><View style={[styles.impactIcon, { backgroundColor: colors.primary }]}><Feather name="zap" size={15} color={colors.primaryForeground} /></View><Text style={[styles.cardKicker, { color: colors.foreground }]}>뉴스 영향도</Text><Text style={[styles.impactScore, { color: colors.primary }]}>{item.impactScore}</Text></View><View style={styles.rowBetween}><View><Text style={[styles.impactSymbol, { color: colors.foreground }]}>{item.relatedSymbols[0]}</Text><Text style={[styles.mutedText, { color: colors.mutedForeground }]}>주요 뉴스가 시장에 미친 영향</Text></View><Metric value={formatPercent(item.priceChange)} label="24시간" color={colors.positive} /><Metric value={`+${item.volumeChange}%`} label="거래량" color={colors.amber} /></View></Pressable>;
}

function Metric({ value, label, color }: { value: string; label: string; color: string }) { const colors = useColors(); return <View style={styles.impactMetric}><Text style={[styles.impactMetricValue, { color }]}>{value}</Text><Text style={[styles.mutedText, { color: colors.mutedForeground }]}>{label}</Text></View>; }

export function TopMovers({ assets }: { assets: MarketAsset[] }) {
  const colors = useColors(); const gainers = [...assets].sort((a, b) => b.change24h - a.change24h).slice(0, 3); const losers = [...assets].sort((a, b) => a.change24h - b.change24h).slice(0, 3);
  return <View style={styles.moversGrid}><View style={[styles.moverColumn, { borderColor: colors.border, backgroundColor: colors.card }]}><Text style={[styles.moverTitle, { color: colors.positive }]}>상승</Text>{gainers.map((asset) => <MoverRow key={asset.symbol} asset={asset} />)}</View><View style={[styles.moverColumn, { borderColor: colors.border, backgroundColor: colors.card }]}><Text style={[styles.moverTitle, { color: colors.negative }]}>하락</Text>{losers.map((asset) => <MoverRow key={asset.symbol} asset={asset} />)}</View></View>;
}

function MoverRow({ asset }: { asset: MarketAsset }) { const colors = useColors(); return <Pressable testID={`mover-${asset.symbol}`} onPress={() => router.push(`/coin/${asset.symbol}`)} style={({ pressed }) => [styles.moverRow, { borderBottomColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><Text style={[styles.symbolText, { color: colors.foreground }]}>{asset.symbol}</Text><Text style={[styles.moverChange, { color: asset.change24h >= 0 ? colors.positive : colors.negative }]}>{formatPercent(asset.change24h)}</Text><Ionicons name="chevron-forward" size={14} color={colors.mutedForeground} /></Pressable>; }

export function WatchlistToggle({ symbol }: { symbol: string }) { const colors = useColors(); const { contains, toggle } = useWatchlist(); const active = contains(symbol); return <Pressable testID={`watchlist-toggle-${symbol}`} onPress={() => toggle(symbol)} style={({ pressed }) => [styles.watchButton, { borderColor: active ? colors.primary : colors.border, backgroundColor: active ? colors.primary : colors.card, opacity: pressed ? 0.7 : 1 }]}><Ionicons name={active ? 'star' : 'star-outline'} size={16} color={active ? colors.primaryForeground : colors.primary} /></Pressable>; }

const styles = StyleSheet.create({
  header: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.5, marginBottom: 5 }, headerTitle: { fontFamily: 'Inter_700Bold', fontSize: 29, letterSpacing: -1.2 }, headerMark: { flexDirection: 'row', alignItems: 'center', gap: 7 }, markDot: { width: 8, height: 8, borderRadius: 4 }, markText: { fontFamily: 'Inter_700Bold', fontSize: 15, letterSpacing: 2 }, iconButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', borderWidth: 1 }, rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  marketCard: { width: 192, minHeight: 142, padding: 16, borderRadius: 16, borderWidth: 1, marginRight: 10, justifyContent: 'space-between' }, marketCardCompact: { width: '100%', minHeight: 144, padding: 16, borderRadius: 16, borderWidth: 1, justifyContent: 'space-between' }, symbolPill: { flexDirection: 'row', alignItems: 'center', gap: 7 }, coinDot: { width: 8, height: 8, borderRadius: 4 }, symbolText: { fontFamily: 'Inter_700Bold', fontSize: 14, letterSpacing: 0.4 }, changeText: { fontFamily: 'Inter_700Bold', fontSize: 13 }, price: { fontFamily: 'Inter_700Bold', fontSize: 25, letterSpacing: -0.8, marginTop: 13 }, compactPrice: { fontFamily: 'Inter_700Bold', fontSize: 24, letterSpacing: -0.8, marginTop: 11 }, mutedText: { fontFamily: 'Inter_500Medium', fontSize: 11 },
  sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 28, marginBottom: 12 }, sectionLabel: { fontFamily: 'Inter_700Bold', fontSize: 17, letterSpacing: -0.4 }, actionText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, breakingCard: { borderWidth: 1, borderLeftWidth: 3, padding: 17, borderRadius: 16, gap: 13 }, newsRow: { borderWidth: 1, padding: 15, borderRadius: 14, gap: 10, marginBottom: 9 }, categoryLine: { flexDirection: 'row', alignItems: 'center', gap: 7 }, liveDot: { width: 6, height: 6, borderRadius: 3 }, categoryText: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 0.7 }, timeText: { fontFamily: 'Inter_500Medium', fontSize: 11, marginLeft: 2 }, breakingTitle: { fontFamily: 'Inter_700Bold', fontSize: 21, lineHeight: 28, letterSpacing: -0.7 }, newsTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 15, lineHeight: 21, letterSpacing: -0.3 }, tagRow: { flexDirection: 'row', gap: 5 }, tinyTag: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 6 }, tinyTagText: { fontFamily: 'Inter_700Bold', fontSize: 10 }, sourceText: { fontFamily: 'Inter_500Medium', fontSize: 10 },
  sentimentCard: { borderRadius: 16, borderWidth: 1, padding: 17, minHeight: 142, position: 'relative' }, cardKicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.1 }, sentimentLabel: { fontFamily: 'Inter_700Bold', fontSize: 27, marginTop: 10, letterSpacing: -0.8 }, sentimentChange: { fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 4 }, gaugeNumber: { position: 'absolute', right: 48, top: 56, fontFamily: 'Inter_700Bold', fontSize: 28 }, impactCard: { borderRadius: 16, borderWidth: 1, padding: 16, marginTop: 10, gap: 15 }, impactHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 }, impactIcon: { width: 25, height: 25, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, impactScore: { fontFamily: 'Inter_700Bold', fontSize: 20, marginLeft: 'auto' }, impactSymbol: { fontFamily: 'Inter_700Bold', fontSize: 24, letterSpacing: -0.5 }, impactMetric: { alignItems: 'flex-end', gap: 4 }, impactMetricValue: { fontFamily: 'Inter_700Bold', fontSize: 14 },
  moversGrid: { flexDirection: 'row', gap: 9 }, moverColumn: { flex: 1, paddingHorizontal: 13, paddingTop: 14, borderWidth: 1, borderRadius: 16 }, moverTitle: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.1, marginBottom: 6 }, moverRow: { minHeight: 39, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, gap: 7 }, moverChange: { fontFamily: 'Inter_700Bold', fontSize: 12, marginLeft: 'auto' }, watchButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
});