import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { Screen } from '@/src/components/Screen';
import { MarketCard, ScreenHeader, SectionHeading, TopMovers } from '@/src/components/MarketPulseUI';
import { useGetMarketOverview } from '@workspace/api-client-react';
export default function MarketsScreen() { const colors = useColors(); const marketQuery = useGetMarketOverview(); const snapshot = marketQuery.data; return <Screen><ScreenHeader eyebrow="UPBIT KRW 실시간" title="시장" onPress={() => router.push('/settings')} /><View style={styles.stats}><Stat label="전체 시가총액" value={snapshot?.totalMarketCap ?? '불러오는 중'} /><Stat label="24시간 거래량" value={snapshot?.totalVolume ?? '불러오는 중'} /><Stat label="BTC 비중" value={snapshot?.btcDominance ?? '불러오는 중'} /></View><SectionHeading label="주요 자산" /><View style={styles.grid}>{(snapshot?.assets ?? []).map((asset) => <View key={asset.symbol} style={styles.gridItem}><MarketCard asset={asset} compact /></View>)}</View>{marketQuery.isError && <Text style={{ color: colors.negative }}>실시간 시세를 불러오지 못했습니다.</Text>}<SectionHeading label="주요 변동" /><TopMovers assets={snapshot?.assets ?? []} /></Screen>; }
function Stat({ label, value }: { label: string; value: string }) { const colors = useColors(); return <View style={[styles.stat, { backgroundColor: colors.card }]}><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>{label}</Text><Text style={[styles.statValue, { color: colors.foreground }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ stats: { flexDirection: 'row', gap: 8, marginBottom: 4 }, stat: { flex: 1, padding: 10, borderRadius: 7 }, statLabel: { fontFamily: 'Inter_700Bold', fontSize: 8, letterSpacing: 0.8 }, statValue: { fontFamily: 'Inter_700Bold', fontSize: 15, marginTop: 7 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, gridItem: { width: '48%' } });