import React, { useState } from 'react';
import { StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { Screen } from '@/src/components/Screen';
import { ScreenHeader } from '@/src/components/MarketPulseUI';
export default function SettingsScreen() { const colors = useColors(); const [alerts, setAlerts] = useState(true); const [compact, setCompact] = useState(false); return <Screen><ScreenHeader eyebrow="환경설정" title="설정" /><View style={[styles.modeCard, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={[styles.modeIcon, { backgroundColor: colors.primary }]}><Ionicons name="radio-outline" size={19} color={colors.primaryForeground} /></View><View style={styles.modeCopy}><Text style={[styles.modeTitle, { color: colors.foreground }]}>목업 데이터 모드</Text><Text style={[styles.modeText, { color: colors.mutedForeground }]}>코인니스 API 연결 전까지 실제 뉴스 흐름을 닮은 데이터를 제공합니다.</Text></View><View style={[styles.liveBadge, { borderColor: colors.primary }]}><Text style={[styles.liveText, { color: colors.primary }]}>켜짐</Text></View></View><Text style={[styles.groupLabel, { color: colors.mutedForeground }]}>앱 설정</Text><SettingRow icon="notifications-outline" title="뉴스 알림" detail="속보와 주요 뉴스 알림" value={alerts} onChange={setAlerts} /><SettingRow icon="list-outline" title="뉴스 목록 간결하게 보기" detail="한 화면에 더 많은 헤드라인 표시" value={compact} onChange={setCompact} /><Text style={[styles.groupLabel, { color: colors.mutedForeground }]}>데이터 출처</Text><Source icon="checkmark-circle" dot="primary" title="목업 시장 데이터" detail="8초마다 자동 갱신" /><Source icon="time-outline" dot="amber" title="코인니스 뉴스 API" detail="API 연결 대기 중" /></Screen>; }
function SettingRow({ icon, title, detail, value, onChange }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; value: boolean; onChange: (value: boolean) => void }) { const colors = useColors(); return <View style={[styles.setting, { borderBottomColor: colors.border }]}><Ionicons name={icon} size={20} color={colors.primary} /><View style={styles.settingCopy}><Text style={[styles.settingTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.settingDetail, { color: colors.mutedForeground }]}>{detail}</Text></View><Switch testID={`setting-${title}`} value={value} onValueChange={onChange} trackColor={{ false: colors.secondary, true: colors.primary }} thumbColor={value ? colors.primaryForeground : colors.mutedForeground} /></View>; }
function Source({ icon, dot, title, detail }: { icon: keyof typeof Ionicons.glyphMap; dot: 'primary' | 'amber'; title: string; detail: string }) { const colors = useColors(); const tone = dot === 'primary' ? colors.primary : colors.amber; return <View style={[styles.sourceRow, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={[styles.sourceDot, { backgroundColor: tone }]} /><View><Text style={[styles.sourceTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.sourceText, { color: colors.mutedForeground }]}>{detail}</Text></View><Ionicons name={icon} size={20} color={tone} style={styles.sourceCheck} /></View>; }
const styles = StyleSheet.create({ modeCard: { borderWidth: 1, borderRadius: 10, padding: 15, flexDirection: 'row', alignItems: 'center', marginBottom: 28 }, modeIcon: { width: 38, height: 38, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, modeCopy: { flex: 1 }, modeTitle: { fontFamily: 'Inter_700Bold', fontSize: 14 }, modeText: { fontFamily: 'Inter_500Medium', fontSize: 11, lineHeight: 16, marginTop: 4 }, liveBadge: { borderWidth: 1, borderRadius: 4, paddingHorizontal: 7, paddingVertical: 5, marginLeft: 8 }, liveText: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1 }, groupLabel: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.4, marginBottom: 8 }, setting: { minHeight: 72, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, gap: 12 }, settingCopy: { flex: 1 }, settingTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, settingDetail: { fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 3 }, sourceRow: { minHeight: 68, borderWidth: 1, borderRadius: 9, padding: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 9 }, sourceDot: { width: 8, height: 8, borderRadius: 4, marginRight: 11 }, sourceTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, sourceText: { fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 3 }, sourceCheck: { marginLeft: 'auto' } });