import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useColors } from '@/hooks/useColors';
import { Screen } from '@/src/components/Screen';
import { ScreenHeader, WatchlistToggle, formatPercent, formatPrice } from '@/src/components/MarketPulseUI';
import { getMockSnapshot } from '@/src/data/mockData';
import { useWatchlist } from '@/src/context/WatchlistContext';
export default function WatchlistScreen() { const colors = useColors(); const { symbols, isLoading } = useWatchlist(); const assets = getMockSnapshot().assets.filter((asset) => symbols.includes(asset.symbol)); return <Screen><ScreenHeader eyebrow="관심 뉴스와 자산" title="관심목록" onPress={() => router.push('/settings')} /><Text style={[styles.intro, { color: colors.mutedForeground }]}>관심 있는 코인과 관련 뉴스를 한눈에 확인하세요.</Text>{isLoading ? <Text style={[styles.emptyText, { color: colors.mutedForeground }]}>관심목록을 불러오는 중…</Text> : assets.length === 0 ? <View style={[styles.empty, { borderColor: colors.border, backgroundColor: colors.card }]}><Ionicons name="star-outline" size={28} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>관심목록이 비어 있습니다</Text><Text style={[styles.emptyText, { color: colors.mutedForeground }]}>시장에서 자산을 추가해 관심목록을 만들어보세요.</Text></View> : <View style={styles.list}>{assets.map((asset) => <Pressable key={asset.symbol} testID={`watchlist-row-${asset.symbol}`} onPress={() => router.push(`/coin/${asset.symbol}`)} style={[styles.row, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={styles.asset}><View style={[styles.assetDot, { backgroundColor: asset.accent }]} /><View><Text style={[styles.symbol, { color: colors.foreground }]}>{asset.symbol}</Text><Text style={[styles.name, { color: colors.mutedForeground }]}>{asset.name}</Text></View></View><View style={styles.priceBlock}><Text style={[styles.price, { color: colors.foreground }]}>{formatPrice(asset.price)}</Text><Text style={[styles.change, { color: asset.change24h >= 0 ? colors.positive : colors.negative }]}>{formatPercent(asset.change24h)}</Text></View><WatchlistToggle symbol={asset.symbol} /></Pressable>)}</View>}</Screen>; }
const styles = StyleSheet.create({ intro: { fontFamily: 'Inter_500Medium', fontSize: 13, lineHeight: 19, maxWidth: 320, marginBottom: 20 }, list: { gap: 9 }, row: { minHeight: 76, borderWidth: 1, borderRadius: 9, padding: 14, flexDirection: 'row', alignItems: 'center' }, asset: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }, assetDot: { width: 9, height: 9, borderRadius: 5 }, symbol: { fontFamily: 'Inter_700Bold', fontSize: 15 }, name: { fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 3 }, priceBlock: { alignItems: 'flex-end', marginRight: 11 }, price: { fontFamily: 'Inter_700Bold', fontSize: 14 }, change: { fontFamily: 'Inter_700Bold', fontSize: 11, marginTop: 4 }, empty: { minHeight: 220, borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center', padding: 28 }, emptyTitle: { fontFamily: 'Inter_700Bold', fontSize: 17, marginTop: 14 }, emptyText: { fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 7 } });