import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { getAsset, mockNews } from '@/src/data/mockData';
import { formatPercent, formatPrice, NewsRow, Sparkline, WatchlistToggle } from '@/src/components/MarketPulseUI';
export default function CoinDetailScreen() { const colors = useColors(); const insets = useSafeAreaInsets(); const { symbol } = useLocalSearchParams<{ symbol: string }>(); const asset = getAsset(symbol ?? 'BTC'); const [range, setRange] = useState('24H'); const related = mockNews.filter((item) => item.relatedSymbols.includes(asset.symbol)); return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 14, paddingBottom: insets.bottom + 40 }]}><Pressable testID="coin-back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.foreground} /><Text style={[styles.backText, { color: colors.foreground }]}>돌아가기</Text></Pressable><View style={styles.coinHead}><View><Text style={[styles.symbol, { color: colors.mutedForeground }]}>{asset.name} · {asset.symbol}</Text><Text style={[styles.price, { color: colors.foreground }]}>{formatPrice(asset.price)}</Text><Text style={[styles.change, { color: asset.change24h >= 0 ? colors.positive : colors.negative }]}>{formatPercent(asset.change24h)} 오늘</Text></View><WatchlistToggle symbol={asset.symbol} /></View><View style={[styles.chart, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={styles.chartHead}><Text style={[styles.chartLabel, { color: colors.mutedForeground }]}>가격 흐름</Text><View style={styles.ranges}>{['24H', '7D', '30D'].map((item) => <Pressable key={item} testID={`range-${item}`} onPress={() => setRange(item)} style={[styles.range, { backgroundColor: range === item ? colors.primary : colors.secondary }]}><Text style={[styles.rangeText, { color: range === item ? colors.primaryForeground : colors.mutedForeground }]}>{item === '24H' ? '24시간' : item === '7D' ? '7일' : '30일'}</Text></Pressable>)}</View></View><Sparkline points={asset.sparkline.concat(asset.sparkline.slice(-4).map((value) => value + 3))} color={asset.change24h >= 0 ? colors.positive : colors.negative} width={320} height={150} strokeWidth={3} /></View><View style={styles.stats}>{[['24시간 거래량', asset.volume24h], ['시가총액', asset.marketCap], ['24시간 고가', formatPrice(asset.high24h)], ['24시간 저가', formatPrice(asset.low24h)]].map(([label, value]) => <View key={label} style={[styles.stat, { borderColor: colors.border, backgroundColor: colors.card }]}><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>{label}</Text><Text style={[styles.statValue, { color: colors.foreground }]}>{value}</Text></View>)}</View><Text style={[styles.section, { color: colors.foreground }]}>관련 뉴스</Text>{related.map((item) => <NewsRow key={item.id} item={item} />)}</ScrollView>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 18 }, back: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 }, backText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, coinHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, symbol: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.3 }, price: { fontFamily: 'Inter_700Bold', fontSize: 38, letterSpacing: -1.6, marginTop: 11 }, change: { fontFamily: 'Inter_700Bold', fontSize: 12, marginTop: 7 }, chart: { borderWidth: 1, borderRadius: 10, padding: 16, marginTop: 27 }, chartHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, chartLabel: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.2 }, ranges: { flexDirection: 'row', gap: 5 }, range: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 4 }, rangeText: { fontFamily: 'Inter_700Bold', fontSize: 9 }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 18 }, stat: { width: '48%', borderWidth: 1, borderRadius: 8, padding: 13 }, statLabel: { fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 0.8 }, statValue: { fontFamily: 'Inter_700Bold', fontSize: 16, marginTop: 8 }, section: { fontFamily: 'Inter_700Bold', fontSize: 17, marginTop: 28, marginBottom: 12 } });