import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { getNews, getAsset } from '@/src/data/mockData';
import { formatPercent, formatPrice, Sparkline, WatchlistToggle } from '@/src/components/MarketPulseUI';
export default function NewsDetailScreen() { const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const item = getNews(id ?? ''); const asset = getAsset(item.relatedSymbols[0]); return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 14, paddingBottom: insets.bottom + 40 }]}><Pressable testID="news-back" onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.foreground} /><Text style={[styles.backText, { color: colors.foreground }]}>Back to news</Text></Pressable><Text style={[styles.category, { color: item.importance === 'breaking' ? colors.negative : colors.primary }]}>{item.importance === 'breaking' ? 'BREAKING' : item.categories.join(' · ')}</Text><Text style={[styles.time, { color: colors.mutedForeground }]}>{item.relativeTime} · {item.source}</Text><Text style={[styles.title, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.body, { color: colors.secondaryForeground }]}>{item.content}</Text><View style={[styles.reaction, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={styles.reactionHead}><View><Text style={[styles.kicker, { color: colors.mutedForeground }]}>MARKET REACTION</Text><Text style={[styles.assetName, { color: colors.foreground }]}>{asset.symbol} · {formatPrice(asset.price)}</Text></View><WatchlistToggle symbol={asset.symbol} /></View><View style={styles.reactionRow}><Reaction label="Before news" value={formatPrice(asset.price * (1 - item.priceChange / 100))} /><Ionicons name="arrow-forward" size={17} color={colors.mutedForeground} /><Reaction label="Now" value={formatPrice(asset.price)} highlight change={item.priceChange} /></View><Sparkline points={asset.sparkline} color={item.priceChange >= 0 ? colors.positive : colors.negative} width={300} height={80} /></View><View style={[styles.scoreRow, { borderTopColor: colors.border }]}><Text style={[styles.kicker, { color: colors.mutedForeground }]}>NEWS IMPACT SCORE</Text><Text style={[styles.score, { color: colors.primary }]}>{item.impactScore}<Text style={[styles.scoreOutOf, { color: colors.mutedForeground }]}> / 100</Text></Text></View></ScrollView>; }
function Reaction({ label, value, highlight, change }: { label: string; value: string; highlight?: boolean; change?: number }) { const colors = useColors(); return <View><Text style={[styles.reactionLabel, { color: colors.mutedForeground }]}>{label}</Text><Text style={[styles.reactionValue, { color: highlight ? colors.foreground : colors.secondaryForeground }]}>{value}</Text>{highlight && <Text style={[styles.reactionChange, { color: colors.positive }]}>{formatPercent(change ?? 0)}</Text>}</View>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 18 }, back: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 }, backText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, category: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.2 }, time: { fontFamily: 'Inter_500Medium', fontSize: 11, marginTop: 7 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, lineHeight: 36, letterSpacing: -1.1, marginTop: 18 }, body: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23, marginTop: 19 }, reaction: { borderWidth: 1, borderRadius: 10, padding: 16, marginTop: 28 }, reactionHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.3 }, assetName: { fontFamily: 'Inter_700Bold', fontSize: 20, marginTop: 8 }, reactionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 24, marginBottom: 21 }, reactionLabel: { fontFamily: 'Inter_500Medium', fontSize: 10, marginBottom: 5 }, reactionValue: { fontFamily: 'Inter_700Bold', fontSize: 17 }, reactionChange: { fontFamily: 'Inter_700Bold', fontSize: 11, marginTop: 4 }, scoreRow: { borderTopWidth: 1, marginTop: 25, paddingTop: 18, flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between' }, score: { fontFamily: 'Inter_700Bold', fontSize: 25 }, scoreOutOf: { fontFamily: 'Inter_500Medium', fontSize: 13 } });