// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/news-impact-widget/BreakingAlert.tsx": () => import("../components/mockups/news-impact-widget/BreakingAlert.tsx"),
  "./components/mockups/news-impact-widget/Current.tsx": () => import("../components/mockups/news-impact-widget/Current.tsx"),
  "./components/mockups/news-impact-widget/LargeImpact.tsx": () => import("../components/mockups/news-impact-widget/LargeImpact.tsx"),
  "./components/mockups/news-impact-widget/MediumTicker.tsx": () => import("../components/mockups/news-impact-widget/MediumTicker.tsx"),
  "./components/mockups/news-impact-widget/SmallGlance.tsx": () => import("../components/mockups/news-impact-widget/SmallGlance.tsx")
};
